[package]
distribution = "2201.13.1"
org = "ballerinax"
name = "huggingface.tei"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [
    "AI/Embeddings",
    "AI/Reranking",
    "HuggingFace",
    "TEI",
    "Embeddings",
    "Semantic Search",
    "Vector Search",
    "Reranking",
    "RAG",
    "BGE",
    "Vendor/HuggingFace",
    "Cost/Free"
]

repository = "https://github.com/ballerina-platform/module-ballerinax-huggingface.tei"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
