// Generated by Ballerina OpenAPI tool and manually sanitized.
// See docs/spec/sanitations.md for changes made post-generation.

import ballerina/data.jsondata;
import ballerina/http;

# Text Embedding Webserver
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(string serviceUrl, ConnectionConfig config =  {}) returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Decode input ids
    #
    # + headers - Headers to be sent with the request 
    # + return - Decoded ids 
    resource isolated function post decode(DecodeRequest payload, map<string|string[]> headers = {}) returns DecodeResponse|error {
        string resourcePath = string `/decode`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get Embeddings. Returns a 424 status code if the model is not an embedding model.
    #
    # + headers - Headers to be sent with the request 
    # + return - Embeddings 
    resource isolated function post embed(EmbedRequest payload, map<string|string[]> headers = {}) returns EmbedResponse|error {
        string resourcePath = string `/embed`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get all Embeddings without Pooling. Returns a 424 status code if the model is not an embedding model.
    #
    # + headers - Headers to be sent with the request 
    # + return - Embeddings 
    resource isolated function post embed_all(EmbedAllRequest payload, map<string|string[]> headers = {}) returns EmbedAllResponse|error {
        string resourcePath = string `/embed_all`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get Sparse Embeddings. Returns a 424 status code if the model is not an embedding model with SPLADE pooling.
    #
    # + headers - Headers to be sent with the request 
    # + return - Embeddings 
    resource isolated function post embed_sparse(EmbedSparseRequest payload, map<string|string[]> headers = {}) returns EmbedSparseResponse|error {
        string resourcePath = string `/embed_sparse`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Health check method
    #
    # + headers - Headers to be sent with the request 
    # + return - Everything is working fine 
    resource isolated function get health(map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/health`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Text Embeddings Inference endpoint info
    #
    # + headers - Headers to be sent with the request 
    # + return - Served model info 
    resource isolated function get info(map<string|string[]> headers = {}) returns Info|error {
        string resourcePath = string `/info`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Prometheus metrics scrape endpoint
    #
    # + headers - Headers to be sent with the request 
    # + return - Prometheus Metrics 
    resource isolated function get metrics(map<string|string[]> headers = {}) returns string|error {
        string resourcePath = string `/metrics`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get Predictions. Returns a 424 status code if the model is not a Sequence Classification model
    #
    # + headers - Headers to be sent with the request 
    # + return - Predictions 
    resource isolated function post predict(PredictRequest payload, map<string|string[]> headers = {}) returns PredictResponse|error {
        string resourcePath = string `/predict`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get Ranks. Returns a 424 status code if the model is not a Sequence Classification model with
    #
    # + headers - Headers to be sent with the request 
    # + return - Ranks 
    resource isolated function post rerank(RerankRequest payload, map<string|string[]> headers = {}) returns RerankResponse|error {
        string resourcePath = string `/rerank`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get Sentence Similarity. Returns a 424 status code if the model is not an embedding model.
    #
    # + headers - Headers to be sent with the request 
    # + return - Sentence Similarity 
    resource isolated function post similarity(SimilarityRequest payload, map<string|string[]> headers = {}) returns SimilarityResponse|error {
        string resourcePath = string `/similarity`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Tokenize inputs
    #
    # + headers - Headers to be sent with the request 
    # + return - Tokenized ids 
    resource isolated function post tokenize(TokenizeRequest payload, map<string|string[]> headers = {}) returns TokenizeResponse|error {
        string resourcePath = string `/tokenize`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # OpenAI compatible route. Returns a 424 status code if the model is not an embedding model.
    #
    # + headers - Headers to be sent with the request 
    # + return - Embeddings 
    resource isolated function post v1/embeddings(OpenAICompatRequest payload, map<string|string[]> headers = {}) returns OpenAICompatResponse|error {
        string resourcePath = string `/v1/embeddings`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }
}
