// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

public type OpenAICompatResponse record {
    OpenAICompatEmbedding[] data;
    OpenAICompatUsage usage;
    string model;
    string 'object;
};

public type EmbeddingModel record {
    string pooling;
};

public type SimilarityResponse float[];

public type TokenizeInput TokenizeInputOneOf1|TokenizeInputTokenizeInputOneOf12;

public type TruncationDirection "Left"|"Right";

# Model input. Can be either a single string, a pair of strings or a batch of mixed single and pairs of strings
public type PredictInput PredictInputOneOf1|PredictInputPredictInputOneOf12|PredictInputPredictInputPredictInputOneOf123;

public type EncodingFormat "float"|"base64";

public type Input InputType|InputOneOf2;

# A pair of strings
@constraint:Array {maxLength: 2, minLength: 2}
public type PredictInputPredictInputOneOf12 string[];

# A batch
public type PredictInputPredictInputPredictInputOneOf123 (string[]|string[])[];

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth?;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type ModelTypeModelTypeOneOf12 record {
    EmbeddingModel embedding;
};

public type TokenizeResponse SimpleToken[][];

public type Prediction record {
    float score;
    string label;
};

public type PredictResponse PredictResponseOneOf1|PredictResponsePredictResponseOneOf12;

public type OpenAICompatEmbedding record {
    @constraint:Int {minValue: 0}
    int index;
    Embedding embedding;
    string 'object;
};

public type PredictRequest record {
    boolean? truncate = false;
    # Model input. Can be either a single string, a pair of strings or a batch of mixed single and pairs of strings
    PredictInput inputs;
    @jsondata:Name {value: "raw_scores"}
    boolean rawScores = false;
    @jsondata:Name {value: "truncation_direction"}
    TruncationDirection truncationDirection = "Right";
};

public type InputType InputTypeOneOf1|InputTypeInputTypeOneOf12;

public type InputIdsInputIdsOneOf12 InputIdsInputIdsOneOf12ItemsArray[];

public type SparseValue record {
    @constraint:Int {minValue: 0}
    int index;
    float value;
};

public type EmbedAllResponse float[][][];

public type OpenAICompatUsage record {
    @jsondata:Name {value: "prompt_tokens"}
    int promptTokens;
    @jsondata:Name {value: "total_tokens"}
    int totalTokens;
};

public type InputIdsOneOf1 InputIdsOneOf1ItemsInteger[];

public type TokenizeInputTokenizeInputOneOf12 string[];

public type InputTypeOneOf1 string;

public type InputOneOf2 InputType[];

public type InputIds InputIdsOneOf1|InputIdsInputIdsOneOf12;

public type Embedding EmbeddingOneOf1|EmbeddingEmbeddingOneOf12;

@constraint:Int {minValue: 0}
public type InputTypeInputTypeOneOf12ItemsInteger int:Signed32;

public type EmbeddingEmbeddingOneOf12 string;

public type InputTypeInputTypeOneOf12 InputTypeInputTypeOneOf12ItemsInteger[];

public type EmbedRequest record {
    boolean? truncate = false;
    Input inputs;
    boolean normalize = true;
    @jsondata:Name {value: "truncation_direction"}
    TruncationDirection truncationDirection = "Right";
    # The number of dimensions that the output embeddings should have. If not set, the original
    # shape of the representation will be returned instead
    int? dimensions?;
    # The name of the prompt that should be used by for encoding. If not set, no prompt
    # will be applied.
    # 
    # Must be a key in the `sentence-transformers` configuration `prompts` dictionary.
    # 
    # For example if ``prompt_name`` is "query" and the ``prompts`` is {"query": "query: ", ...},
    # then the sentence "What is the capital of France?" will be encoded as
    # "query: What is the capital of France?" because the prompt text will be prepended before
    # any text to encode
    @jsondata:Name {value: "prompt_name"}
    string? promptName = "null";
};

public type EmbedSparseRequest record {
    boolean? truncate = false;
    Input inputs;
    @jsondata:Name {value: "truncation_direction"}
    TruncationDirection truncationDirection = "Right";
    # The name of the prompt that should be used by for encoding. If not set, no prompt
    # will be applied.
    # 
    # Must be a key in the `sentence-transformers` configuration `prompts` dictionary.
    # 
    # For example if ``prompt_name`` is "query" and the ``prompts`` is {"query": "query: ", ...},
    # then the sentence "What is the capital of France?" will be encoded as
    # "query: What is the capital of France?" because the prompt text will be prepended before
    # any text to encode
    @jsondata:Name {value: "prompt_name"}
    string? promptName = "null";
};

public type ClassifierModel record {
    record {|string...;|} id2label;
    record {|int...;|} label2id;
};

public type DecodeResponse string[];

public type RerankRequest record {
    string[] texts;
    boolean? truncate = false;
    @jsondata:Name {value: "return_text"}
    boolean returnText = false;
    string query;
    @jsondata:Name {value: "raw_scores"}
    boolean rawScores = false;
    @jsondata:Name {value: "truncation_direction"}
    TruncationDirection truncationDirection = "Right";
};

public type TokenizeRequest record {
    TokenizeInput inputs;
    @jsondata:Name {value: "add_special_tokens"}
    boolean addSpecialTokens = true;
    # The name of the prompt that should be used by for encoding. If not set, no prompt
    # will be applied.
    # 
    # Must be a key in the `sentence-transformers` configuration `prompts` dictionary.
    # 
    # For example if ``prompt_name`` is "query" and the ``prompts`` is {"query": "query: ", ...},
    # then the sentence "What is the capital of France?" will be encoded as
    # "query: What is the capital of France?" because the prompt text will be prepended before
    # any text to encode
    @jsondata:Name {value: "prompt_name"}
    string? promptName = "null";
};

public type RerankResponse Rank[];

public type PredictResponseOneOf1 Prediction[];

public type SimilarityRequest record {
    SimilarityInput inputs;
    SimilarityParameters? parameters = ();
};

public type EmbeddingOneOf1 float[];

public type EmbedResponse float[][];

public type EmbedSparseResponse SparseValue[][];

public type SimilarityParameters record {
    boolean? truncate = false;
    @jsondata:Name {value: "truncation_direction"}
    TruncationDirection truncationDirection = "Right";
    # The name of the prompt that should be used by for encoding. If not set, no prompt
    # will be applied.
    # 
    # Must be a key in the `sentence-transformers` configuration `prompts` dictionary.
    # 
    # For example if ``prompt_name`` is "query" and the ``prompts`` is {"query": "query: ", ...},
    # then the sentence "What is the capital of France?" will be encoded as
    # "query: What is the capital of France?" because the prompt text will be prepended before
    # any text to encode
    @jsondata:Name {value: "prompt_name"}
    string? promptName = "null";
};

public type OpenAICompatRequest record {
    Input input;
    @jsondata:Name {value: "encoding_format"}
    EncodingFormat encodingFormat = "float";
    string? model?;
    string? user?;
    int? dimensions?;
};

public type InputIdsInputIdsOneOf12ItemsArray InputIdsInputIdsOneOf12ItemsArrayItemsInteger[];

public type DecodeRequest record {
    @jsondata:Name {value: "skip_special_tokens"}
    boolean skipSpecialTokens = true;
    InputIds ids;
};

public type PredictInputPredictInputPredictInputOneOf123Itemsnull string[]|string[];

public type Rank record {
    float score;
    @constraint:Int {minValue: 0}
    int index;
    string? text = "null";
};

public type Info record {
    # Router Parameters
    @jsondata:Name {value: "max_concurrent_requests"}
    int maxConcurrentRequests;
    @jsondata:Name {value: "max_client_batch_size"}
    int maxClientBatchSize;
    @jsondata:Name {value: "model_type"}
    ModelType modelType;
    @jsondata:Name {value: "max_batch_requests"}
    int? maxBatchRequests?;
    # Model info
    @jsondata:Name {value: "model_id"}
    string modelId;
    string? sha?;
    # Router Info
    string version;
    @jsondata:Name {value: "auto_truncate"}
    boolean autoTruncate;
    @jsondata:Name {value: "max_input_length"}
    int maxInputLength;
    @jsondata:Name {value: "model_dtype"}
    string modelDtype;
    @jsondata:Name {value: "model_sha"}
    string? modelSha?;
    @jsondata:Name {value: "tokenization_workers"}
    int tokenizationWorkers;
    @jsondata:Name {value: "max_batch_tokens"}
    int maxBatchTokens;
    @jsondata:Name {value: "docker_label"}
    string? dockerLabel?;
    @jsondata:Name {value: "served_model_name"}
    string servedModelName;
};

public type SimilarityInput record {
    # A list of strings which will be compared against the source_sentence
    string[] sentences;
    # The string that you wish to compare the other strings with. This can be a phrase, sentence,
    # or longer passage, depending on the model being used
    @jsondata:Name {value: "source_sentence"}
    string sourceSentence;
};

public type ModelTypeModelTypeModelTypeOneOf123 record {
    ClassifierModel reranker;
};

public type EmbedAllRequest record {
    boolean? truncate = false;
    Input inputs;
    @jsondata:Name {value: "truncation_direction"}
    TruncationDirection truncationDirection = "Right";
    # The name of the prompt that should be used by for encoding. If not set, no prompt
    # will be applied.
    # 
    # Must be a key in the `sentence-transformers` configuration `prompts` dictionary.
    # 
    # For example if ``prompt_name`` is "query" and the ``prompts`` is {"query": "query: ", ...},
    # then the sentence "What is the capital of France?" will be encoded as
    # "query: What is the capital of France?" because the prompt text will be prepended before
    # any text to encode
    @jsondata:Name {value: "prompt_name"}
    string? promptName = "null";
};

public type ModelTypeOneOf1 record {
    ClassifierModel classifier;
};

public type ModelType ModelTypeOneOf1|ModelTypeModelTypeOneOf12|ModelTypeModelTypeModelTypeOneOf123;

public type TokenizeInputOneOf1 string;

# A single string
public type PredictInputOneOf1 string;

public type PredictResponsePredictResponseOneOf12 Prediction[][];

@constraint:Int {minValue: 0}
public type InputIdsOneOf1ItemsInteger int:Signed32;

public type SimpleToken record {
    boolean special;
    int? stop?;
    int? 'start?;
    @constraint:Int {minValue: 0}
    int:Signed32 id;
    string text;
};

public type InputIdsInputIdsOneOf12ItemsArrayItemsInteger int:Signed32;
